# Generated by Django 4.0 on 2023-11-30 19:52

import admi.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Entrer un numéro de 8 chiffres', regex='^\\d{8}$')])),
                ('fonction', models.CharField(choices=[('Superviseur', 'Superviseur'), ('Comptable', 'Comptable'), ('Administratif', 'Administratif'), ('Delegué', 'Delegué'), ('Livreur', 'Livreur'), ('Coursier', 'Coursier'), ('Administrateur', 'Administrateur')], default='Delegué', max_length=50)),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='PasserConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('Congé de Maladie', 'Congé de Maladie'), ('Congé Annuel', 'Congé Annuel')], default='Congé Annuel', max_length=50)),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('duree', models.PositiveIntegerField()),
                ('Accepte', models.BooleanField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CongEmp', to='admi.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2015), admi.models.max_value_current_year])),
                ('solde_conge', models.PositiveIntegerField(default=0)),
                ('solde_conge_maladie', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nbrEmp', to='admi.employe')),
            ],
            options={
                'ordering': ['annee', 'employee'],
            },
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['user'], name='admi_employ_user_id_403b97_idx'),
        ),
    ]
