# Generated by Django 4.0 on 2023-12-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admi', '0002_alter_compte_options_alter_employe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passerconge',
            name='Refuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passerconge',
            name='Accepte',
            field=models.BooleanField(default=False),
        ),
    ]
