# Generated by Django 4.0 on 2023-12-01 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admi', '0003_passerconge_refuse_alter_passerconge_accepte'),
    ]

    operations = [
        migrations.AddField(
            model_name='passerconge',
            name='DateDemande',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
